### ISSUE TITLE
How to create an intermediate CA certificate that recognized valid by CertPathValidator

### ISSUE THREAD

**Issue by torao** [torao/carillon#1]
単体テストのために OpenSSL を使用して中間 CA 証明書を作成したところ `CertPathValidator` が無効と判断した。どのように `CertPathValidator` が正しいと判断するかを調査し `openssl` コマンドでの作成方法をドキュメントに記載する。

**Comment by torao** [comment]
#### 分かったこと
* 証明書チェーンは末端から順に並び末尾がルート CA 証明書でなければならない。
* trusted anchor は自己署名証明書でなければならない。
* CA は URL 経由で CRL を参照できるようにすると OCSP Responder と言うものが使える。

#### Certificate does not specify OCSP responder
`java.security.cert.CertPathValidatorException: Certificate does not specify OCSP responder` は (ルート?) CA 証明書の中に CRL の参照先が含まれていないために起きる。先に CRLS を参照し失敗しても OCSP Responder が起動しないように NO_FALLBACK を指定すれば回避可能か?

```scala
revocationChecker.setOptions(EnumSet.of(REFER_CRLS, NO_FALLBACK))
```
X.509v3 に CRL URL を追加する方法は以下を参照。
* https://stackoverflow.com/questions/11966123/howto-create-a-certificate-using-openssl-including-a-crl-distribution-point
* https://www.pixelstech.net/article/1445498968-Generate-certificate-with-cRLDistributionPoints-extension-using-OpenSSL

#### Could not determine revocation status
`java.security.cert.CertPathValidatorException: Could not determine revocation status` の対処方法が不明。以下のように Revocation を無効化しても発生する。

```scala
params.setRevocationEnabled(false)
```

#### Path does not chain with any of the trust anchors
証明書チェーンが trust anchor を含んでいないときに発生するエラーだが、チェーン内の証明書の順序として末尾がルート CA 証明書ではない場合に発生することから、末尾の証明書のみを trust anchor として検証しているらしい。証明書チェーンは端からルート CA に向かう順序で保存しなければならない。

-----
```json
{
  "type" : "X.509",
  "certs" : [ {
    "fingerprint" : "SHA1:53:AC:8D:A0:5F:44:0E:8D:57:F2:72:E1:CE:0E:57:00:E1:3E:03:DC",
    "basic-constraints" : 2147483647,
    "extended-key-usage" : [ ],
    "issuer" : {
      "alternative-names" : [ ],
      "unique-id" : "",
      "principal" : {
        "name" : "CN=ica01,OU=Unit Test,O=Carillon,ST=Tokyo,C=JP"
      }
    },
    "subject" : {
      "alternative-names" : [ ],
      "unique-id" : [ ],
      "principal" : {
        "name" : "CN=ica02,OU=Unit Test,O=Carillon,ST=Tokyo,C=JP"
      }
    },
    "key-usage" : [ ],
    "not-after" : "2020-02-17T05:46:46.000",
    "not-before" : "2019-02-17T05:46:46.000",
    "serial-number" : 16647459613962913678,
    "sig-alg-name" : "SHA256withECDSA",
    "sig-alg-oid" : "1.2.840.10045.4.3.2",
    "sig-alg-params" : "",
    "signature" : "3045022100ed2e534c9ba263e6a6d982c4d7dda7ffc76c9d82f287d68ff352ddcb8529aa4802200089bf80cecf5365332089fb3b61e3184e7ed37aaf29709c71dc551b98c39b05",
    "tbs-certificate" : "30820195a003020102020900e707a8511eebc78e300a06082a8648ce3d0403023054310b3009060355040613024a50310e300c06035504080c05546f6b796f3111300f060355040a0c08436172696c6c6f6e31123010060355040b0c09556e69742054657374310e300c06035504030c056963613031301e170d3139303231363230343634365a170d3230303231363230343634365a3054310b3009060355040613024a50310e300c06035504080c05546f6b796f3111300f060355040a0c08436172696c6c6f6e31123010060355040b0c09556e69742054657374310e300c06035504030c0569636130323059301306072a8648ce3d020106082a8648ce3d030107034200046002718239459a74fdd35cac4645375e7d4072ad654a641c882cae9faa1f2ec541856153b1f4b14e23c5d904c9c565646d6d76eda55fa3d4258f7f541a7c1080a350304e301d0603551d0e0416041474fe0dcffd4a0479f0e76d833f75225c4bb100de301f0603551d23041830168014c8aadf4179d1c6124598a8a7f72df512e7aeef73300c0603551d13040530030101ff",
    "version" : 3,
    "extension-value" : {
      "2.5.29.14" : "0416041474fe0dcffd4a0479f0e76d833f75225c4bb100de",
      "2.5.29.19" : "040530030101ff",
      "2.5.29.35" : "041830168014c8aadf4179d1c6124598a8a7f72df512e7aeef73"
    },
    "type" : "X.509"
  }, {
    "fingerprint" : "SHA1:19:58:1A:54:44:B0:65:2A:DC:3B:CF:E9:89:A3:3B:34:17:C7:31:D2",
    "basic-constraints" : 2147483647,
    "extended-key-usage" : [ ],
    "issuer" : {
      "alternative-names" : [ ],
      "unique-id" : "",
      "principal" : {
        "name" : "CN=Carillon Unit Test CA,OU=QA Section,O=Carillon,ST=Tokyo,C=JP"
      }
    },
    "subject" : {
      "alternative-names" : [ ],
      "unique-id" : [ ],
      "principal" : {
        "name" : "CN=ica01,OU=Unit Test,O=Carillon,ST=Tokyo,C=JP"
      }
    },
    "key-usage" : [ ],
    "not-after" : "2020-02-17T05:46:44.000",
    "not-before" : "2019-02-17T05:46:44.000",
    "serial-number" : 17780002978628225542,
    "sig-alg-name" : "SHA256withECDSA",
    "sig-alg-oid" : "1.2.840.10045.4.3.2",
    "sig-alg-params" : "",
    "signature" : "3045022002acc9094823a898fcbc356f35e851541cb803339c669699a54c5acd6e6906d3022100f874d61a78bc7765b36429d5c2b18c17ac7a906a165d976431c2fb8d13a87788",
    "tbs-certificate" : "308201a6a003020102020900f6bf4281ae85ca06300a06082a8648ce3d0403023065310b3009060355040613024a50310e300c06035504080c05546f6b796f3111300f060355040a0c08436172696c6c6f6e31133011060355040b0c0a51412053656374696f6e311e301c06035504030c15436172696c6c6f6e20556e69742054657374204341301e170d3139303231363230343634345a170d3230303231363230343634345a3054310b3009060355040613024a50310e300c06035504080c05546f6b796f3111300f060355040a0c08436172696c6c6f6e31123010060355040b0c09556e69742054657374310e300c06035504030c0569636130313059301306072a8648ce3d020106082a8648ce3d03010703420004aa9e777c6d01f6f3809bbf49435b69dc6739a0f3f578e07433d06112c2c298bd610124e79e4ed9f5755c7e50a7d82e8a27c7f94395463ac04f473e59972f46d6a350304e301d0603551d0e04160414c8aadf4179d1c6124598a8a7f72df512e7aeef73301f0603551d230418301680146e12b7f49317ff73ef4a2c6a670acbbe0d490384300c0603551d13040530030101ff",
    "version" : 3,
    "extension-value" : {
      "2.5.29.14" : "04160414c8aadf4179d1c6124598a8a7f72df512e7aeef73",
      "2.5.29.19" : "040530030101ff",
      "2.5.29.35" : "0418301680146e12b7f49317ff73ef4a2c6a670acbbe0d490384"
    },
    "type" : "X.509"
  }, {
    "fingerprint" : "SHA1:F0:06:32:8E:49:64:35:85:6F:8E:42:02:5E:71:1B:8D:29:1F:4D:68",
    "basic-constraints" : 2147483647,
    "extended-key-usage" : [ ],
    "issuer" : {
      "alternative-names" : [ ],
      "unique-id" : "",
      "principal" : {
        "name" : "CN=Carillon Unit Test CA,OU=QA Section,O=Carillon,ST=Tokyo,C=JP"
      }
    },
    "subject" : {
      "alternative-names" : [ ],
      "unique-id" : [ ],
      "principal" : {
        "name" : "CN=Carillon Unit Test CA,OU=QA Section,O=Carillon,ST=Tokyo,C=JP"
      }
    },
    "key-usage" : [ ],
    "not-after" : "2020-02-17T05:46:42.000",
    "not-before" : "2019-02-17T05:46:42.000",
    "serial-number" : 17780002978628225541,
    "sig-alg-name" : "SHA256withECDSA",
    "sig-alg-oid" : "1.2.840.10045.4.3.2",
    "sig-alg-params" : "",
    "signature" : "304402202fa3fe31e877d35522495dc383781d8c23a6121a02a8ed74ab8a1a939ce98d4702205037b1a68a6de51bec84cde17368db6e7adfecb54d56e79429fc4c2cf3cdd368",
    "tbs-certificate" : "308201b7a003020102020900f6bf4281ae85ca05300a06082a8648ce3d0403023065310b3009060355040613024a50310e300c06035504080c05546f6b796f3111300f060355040a0c08436172696c6c6f6e31133011060355040b0c0a51412053656374696f6e311e301c06035504030c15436172696c6c6f6e20556e69742054657374204341301e170d3139303231363230343634325a170d3230303231363230343634325a3065310b3009060355040613024a50310e300c06035504080c05546f6b796f3111300f060355040a0c08436172696c6c6f6e31133011060355040b0c0a51412053656374696f6e311e301c06035504030c15436172696c6c6f6e20556e697420546573742043413059301306072a8648ce3d020106082a8648ce3d030107034200046eab2e7810324e151933eb1b32284dabf65c263fd4b2e4000af89706c44808ca0e9a7b4e8ca0c8fde476b3a9752a5b18abf7450495b1f2f5960876a8fe7de127a350304e301d0603551d0e041604146e12b7f49317ff73ef4a2c6a670acbbe0d490384301f0603551d230418301680146e12b7f49317ff73ef4a2c6a670acbbe0d490384300c0603551d13040530030101ff",
    "version" : 3,
    "extension-value" : {
      "2.5.29.14" : "041604146e12b7f49317ff73ef4a2c6a670acbbe0d490384",
      "2.5.29.19" : "040530030101ff",
      "2.5.29.35" : "0418301680146e12b7f49317ff73ef4a2c6a670acbbe0d490384"
    },
    "type" : "X.509"
  } ]
}
```
```
java.security.cert.CertPathValidatorException: Could not determine revocation status
	at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:233)
	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:141)
	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:80)
	at java.base/java.security.cert.CertPathValidator.validate(CertPathValidator.java:309)
	at io.asterisque.carillon.auth.Algorithms$CertificateChain$.$anonfun$validate$1(Algorithms.scala:83)
	at scala.util.Try$.apply(Try.scala:213)
	at io.asterisque.carillon.auth.Algorithms$CertificateChain$.validate(Algorithms.scala:83)
	at io.asterisque.carillon.auth.TrustedCertificates.acceptable(TrustedCertificates.scala:109)
	at io.asterisque.carillon.auth.TrustedCertificates.$anonfun$install$1(TrustedCertificates.scala:62)
	at io.asterisque.carillon.auth.TrustedCertificates.$anonfun$install$1$adapted(TrustedCertificates.scala:60)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike.map(TraversableLike.scala:237)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
	at scala.collection.immutable.List.map(List.scala:298)
	at io.asterisque.carillon.auth.TrustedCertificates.install(TrustedCertificates.scala:60)
	at io.asterisque.carillon.auth.Authority.install(Authority.scala:53)
	at io.asterisque.carillon.auth.AuthoritySpec.$anonfun$intermediateCertificateChain$2(AuthoritySpec.scala:104)
	at io.asterisque.carillon.package$.using(package.scala:19)
	at io.asterisque.carillon.auth.AuthoritySpec.$anonfun$intermediateCertificateChain$1(AuthoritySpec.scala:102)
	at io.asterisque.carillon.Utils$fs$.temp(Utils.scala:139)
	at io.asterisque.carillon.auth.AuthoritySpec.intermediateCertificateChain(AuthoritySpec.scala:82)
	at io.asterisque.carillon.auth.AuthoritySpec.$anonfun$is$4(AuthoritySpec.scala:20)
	at org.specs2.matcher.MatchResult$$anon$12.$anonfun$asResult$1(MatchResult.scala:344)
	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:22)
	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:21)
	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:123)
	at org.specs2.execute.Result$$anon$11.asResult(Result.scala:246)
	at org.specs2.execute.AsResult$.apply(AsResult.scala:32)
	at org.specs2.matcher.MatchResult$$anon$12.asResult(MatchResult.scala:344)
	at org.specs2.execute.AsResult$.apply(AsResult.scala:32)
	at org.specs2.specification.core.AsExecution$$anon$1.$anonfun$execute$1(AsExecution.scala:17)
	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:22)
	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:21)
	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:123)
	at org.specs2.execute.Result$$anon$11.asResult(Result.scala:246)
	at org.specs2.execute.AsResult$.apply(AsResult.scala:32)
	at org.specs2.execute.AsResult$.$anonfun$safely$1(AsResult.scala:40)
	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:22)
	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:21)
	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:123)
	at org.specs2.execute.AsResult$.safely(AsResult.scala:40)
	at org.specs2.specification.core.Execution$.$anonfun$result$1(Execution.scala:310)
	at org.specs2.specification.core.Execution$.$anonfun$withEnvSync$3(Execution.scala:328)
	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:22)
	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:21)
	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:123)
	at org.specs2.execute.Result$$anon$11.asResult(Result.scala:246)
	at org.specs2.execute.AsResult$.apply(AsResult.scala:32)
	at org.specs2.execute.AsResult$.$anonfun$safely$1(AsResult.scala:40)
	at org.specs2.execute.ResultExecution.execute(ResultExecution.scala:22)
	at org.specs2.execute.ResultExecution.execute$(ResultExecution.scala:21)
	at org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:123)
	at org.specs2.execute.AsResult$.safely(AsResult.scala:40)
	at org.specs2.specification.core.Execution$.$anonfun$withEnvSync$2(Execution.scala:328)
	at org.specs2.specification.core.Execution.$anonfun$startExecution$3(Execution.scala:136)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run$$$capture(Promise.scala:64)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.security.cert.CertPathValidatorException: Could not determine revocation status
	at java.base/sun.security.provider.certpath.RevocationChecker.buildToNewKey(RevocationChecker.java:1110)
	at java.base/sun.security.provider.certpath.RevocationChecker.verifyWithSeparateSigningKey(RevocationChecker.java:930)
	at java.base/sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:603)
	at java.base/sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:464)
	at java.base/sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:366)
	at java.base/sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:336)
	at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
	... 66 common frames omitted
-----
sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
	at java.base/sun.security.provider.certpath.RevocationChecker.buildToNewKey(RevocationChecker.java:1042)
	at java.base/sun.security.provider.certpath.RevocationChecker.verifyWithSeparateSigningKey(RevocationChecker.java:930)
	at java.base/sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:603)
	at java.base/sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:464)
	at java.base/sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:366)
	at java.base/sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:336)
...
```

**Comment by torao** [comment]
`Could not determine revocation status` のエラーを回避する方法がはっきり分からないため `CertPathValidator` による検証は `PKIXRevocationChecker.Option.ONLY_END_ENTITY`、つまり末尾が trust anchor のいずれかと一致するかのみを検証するようにして作業を進めることにする。

チェーンが CA の署名によって連結されていること、証明書チェーンのいずれも CRL に該当しないことは自前で実装を行う。
